// ui/src/components/AppSelect.tsx
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type ISelectOption = {
  label: string;
  value: string;
};

interface Props {
  name: string;
  placeholder?: string;
  defaultValue?: string;
  options: ISelectOption[];
  disabled?: boolean;
}

function AppSelect({
  name,
  placeholder,
  defaultValue,
  options,
  disabled = false,
}: Props) {
  return (
    <Select name={name} defaultValue={defaultValue} disabled={disabled}>
      <SelectTrigger>
        <SelectValue placeholder={placeholder} />
      </SelectTrigger>
      <SelectContent>
        {options.map((opt) => (
          <SelectItem value={opt.value} key={opt.value}>{opt.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

export default AppSelect;

// ui/src/components/AppSelect.vue
<script setup lang="ts">
import {
    Select,
    SelectContent,
    SelectGroup,
    SelectItem,
    SelectLabel,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select'

export interface IOption {
    label: string
    value: string
}

defineProps<{
    options: IOption[]
    name: string
    label: string
    placeholder?: string
    required?: boolean
    defaultValue?: string
}>()
</script>

<template>
    <Select :name="name" :required="required ?? false" :defaultValue>
        <SelectTrigger>
            <SelectValue :placeholder />
        </SelectTrigger>

        <SelectContent>
            <SelectGroup>
                <SelectLabel>{{ label }}</SelectLabel>

                <SelectItem v-for="option in options" :key="option.value" :value="option.value">
                    {{ option.label }}
                </SelectItem>
            </SelectGroup>
        </SelectContent>
    </Select>
</template>
